// Textos de practica para cada tiempo (mas cortos o mas largos segun el tiempo)
export const timeTexts = {
  15: [
    "La lectura es una ventana al conocimiento. Los buenos libros nos transportan a otros mundos. Leer habitualmente mejora nuestro vocabulario y comprension.",
    "El ejercicio fisico es esencial para la salud. Treinta minutos diarios pueden marcar la diferencia. Combinar cardio y fuerza da mejores resultados.",
    "Viajar amplia nuestra perspectiva del mundo. Conocer nuevas culturas enriquece el espiritu. Las experiencias vividas son el mejor souvenir.",
    "La musica tiene el poder de cambiar nuestro estado de animo. Las melodias evocan recuerdos y emociones. El ritmo nos conecta con nuestro interior.",
    "El cine es un arte que combina narrativa visual y sonora. Las grandes peliculas perduran en el tiempo. Cada director imprime su estilo unico.",
  ],
  30: [
    "La lectura regular no solo amplia nuestro vocabulario sino que tambien mejora nuestra capacidad para entender conceptos complejos. Los libros nos permiten vivir mil vidas diferentes desde la comodidad de nuestro hogar. La literatura clasica y contemporanea ofrece perspectivas unicas sobre la condicion humana.",
    "Mantener una rutina de ejercicio constante tiene beneficios que van mas alla de lo fisico. La actividad fisica regular mejora nuestro estado de animo y reduce el estres. Encontrar un deporte o actividad que disfrutemos hace mas facil mantener el habito a largo plazo.",
    "Los viajes nos permiten experimentar diferentes culturas, gastronomias y paisajes que enriquecen nuestra vida. Planificar un viaje puede ser casi tan gratificante como realizarlo. Las experiencias vividas mientras viajamos crean recuerdos que perduran toda la vida.",
    "La cocina casera no solo es mas saludable sino tambien mas economica que comer fuera regularmente. Aprender tecnicas basicas de cocina puede transformar ingredientes simples en platos deliciosos. Cocinar en familia o con amigos fortalece lazos y crea tradiciones.",
    "La fotografia nos permite capturar momentos unicos y preservarlos para siempre. Una buena fotografia puede contar una historia completa sin necesidad de palabras. El arte de la composicion y la luz esta al alcance de cualquiera con una camara basica o un smartphone.",
  ],
  60: [
    "La literatura ha sido a lo largo de la historia un reflejo de la sociedad y una ventana a mundos imaginarios que expanden nuestra comprension del ser humano. Los grandes clasicos literarios siguen siendo relevantes porque abordan temas universales como el amor, la ambicion, el poder y la busqueda de sentido. La lectura regular no solo nos proporciona conocimiento y entretenimiento, sino que tambien desarrolla nuestra empatia al permitirnos experimentar la vida desde diferentes perspectivas y contextos historicos o culturales.",
    "El oceano, que cubre mas del setenta por ciento de la superficie terrestre, sigue siendo uno de los grandes misterios de nuestro planeta. Los cientificos estiman que conocemos menos del cinco por ciento de lo que hay en sus profundidades. La exploracion oceanica moderna ha revelado ecosistemas unicos en torno a fuentes hidrotermales, criaturas que pueden sobrevivir en condiciones extremas, y complejas interacciones entre especies que nos ayudan a entender mejor la biodiversidad y los delicados equilibrios de la naturaleza.",
    "La musica clasica europea, desde el barroco hasta el romanticismo, representa uno de los logros artisticos mas importantes de la humanidad. Compositores como Bach, Mozart y Beethoven crearon obras que siguen conmoviendo a audiencias siglos despues de su creacion. El estudio de la teoria musical revela matematicas complejas, patrones y estructuras que demuestran la profunda conexion entre el arte y la ciencia. La capacidad de la musica para provocar emociones intensas esta ligada a como nuestro cerebro procesa los patrones sonoros y las expectativas melodicas.",
    "Las tradiciones culinarias de cada pais reflejan su historia, geografia y valores culturales a traves de ingredientes, tecnicas y rituales asociados con la comida. La gastronomia francesa, reconocida por su sofisticacion y tecnica refinada, contrasta con la simplicidad y frescura de la cocina mediterranea o la complejidad de sabores de las cocinas asiaticas. Los platos tradicionales suelen contar historias de adaptacion, creatividad y supervivencia, transformando ingredientes locales disponibles en preparaciones que han perdurado generaciones y se han convertido en señas de identidad cultural.",
    "El ajedrez, con mas de mil quinientos años de historia, sigue fascinando a millones de personas en todo el mundo por su perfecta combinacion de estrategia, tactica y psicologia. Este juego, que se desarrolla en un tablero de sesenta y cuatro casillas con treinta y dos piezas iniciales, ofrece posibilidades casi infinitas: hay mas combinaciones posibles de movimientos que atomos en el universo observable. Los grandes maestros de ajedrez pueden visualizar multiples secuencias de movimientos con antelacion, evaluando constantemente patrones, amenazas y oportunidades en un ejercicio mental que combina memoria, intuicion y calculo puro.",
  ],
  120: [
    "La historia del arte occidental refleja la evolucion del pensamiento humano a traves de los siglos, desde las representaciones naturalistas del Renacimiento hasta las rupturas formales de las vanguardias del siglo XX. Leonardo da Vinci, quizas el ejemplo mas celebre del hombre renacentista, combino su talento artistico con una curiosidad cientifica insaciable que lo llevo a diseccionar cadaveres para entender mejor la anatomia humana y mejorar sus pinturas. Siglos despues, artistas como Picasso desafiaron las convenciones establecidas fragmentando la realidad en multiples perspectivas simultaneas, influenciados por los avances cientificos que cuestionaban nuestra percepcion del espacio y el tiempo. El arte contemporaneo continua esta tradicion de dialogo con su epoca, incorporando nuevas tecnologias y abordando preocupaciones actuales como la identidad, la globalizacion y la crisis climatica, demostrando que el impulso creativo humano sigue encontrando formas de expresion relevantes en cada periodo historico.",
    "Los grandes ecosistemas forestales del planeta, como la Amazonia, no solo albergan una extraordinaria biodiversidad sino que tambien juegan un papel crucial en la regulacion del clima global a traves de la captacion de carbono y la generacion de lluvia. Un solo hectarea de selva tropical puede contener mas de cuatrocientas especies de arboles diferentes, cada una sosteniendo complejas redes de vida que incluyen desde microorganismos del suelo hasta mamiferos arboreos y aves especializadas. La interaccion entre especies ha generado fascinantes adaptaciones evolutivas: flores que imitan la apariencia de insectos para atraer polinizadores especificos, plantas que establecen relaciones simbioticas con hormigas para su proteccion, o arboles que se comunican entre si a traves de redes subterraneas de hongos. La conservacion de estos ecosistemas no solo es importante por su valor intrinseco, sino tambien porque muchos medicamentos modernos derivan de compuestos descubiertos en plantas selvaticas, y numerosas especies aun no descubiertas podrian contener soluciones para desafios futuros de la humanidad.",
    "La arquitectura tradicional japonesa representa una aproximacion unica a la relacion entre el espacio construido y el entorno natural, caracterizada por la simplicidad, la asimetria y el uso de materiales naturales. El concepto de 'ma', que puede entenderse como el espacio significativo entre elementos, es fundamental en esta tradicion, creando ritmos visuales y permitiendo que el vacio tenga tanta importancia como lo construido. A diferencia de la arquitectura occidental que historicamente ha buscado permanencia y monumentalidad, las estructuras japonesas tradicionales aceptan la temporalidad, utilizando materiales como la madera y el papel que envejecen con gracia y requieren renovacion periodica. Los jardines japoneses, diseñados para ser contemplados desde verandas especificas, funcionan como extensiones del espacio interior y expresan filosofias zen mediante composiciones cuidadosamente planificadas que recrean paisajes naturales en miniatura. Esta sensibilidad estetica ha influido profundamente en el movimiento moderno arquitectonico a traves de figuras como Frank Lloyd Wright, quien estudio las proporciones y la integracion con el paisaje de los templos japoneses, y continua inspirando aproximaciones contemporaneas a la sostenibilidad y la armonia con el entorno.",
    "El desarrollo de la escritura representa uno de los avances mas significativos en la historia de la humanidad, permitiendo la transmision precisa de conocimiento a traves del tiempo y el espacio. Los primeros sistemas de escritura surgieron independientemente en varias civilizaciones—Mesopotamia, Egipto, China e India—evolucionando desde representaciones pictoricas directas hasta simbolos cada vez mas abstractos. La invencion de la imprenta de tipos moviles por Gutenberg en el siglo XV revoluciono el acceso al conocimiento escrito, democratizando la informacion que antes estaba limitada a elites religiosas y politicas. Este avance tecnologico fue fundamental para la difusion de las ideas del Renacimiento y la Reforma, alterando permanentemente el equilibrio de poder intelectual en Europa. En la actualidad, la transicion hacia medios digitales representa otro cambio paradigmatico en como creamos, compartimos y consumimos texto escrito, con implicaciones profundas para la educacion, el periodismo y la preservacion cultural. A pesar de las multiples transformaciones en su forma, la escritura sigue siendo el principal vehiculo para la transmision precisa de ideas complejas, conectando generaciones a traves del tiempo mediante la fijacion del pensamiento humano en forma duradera.",
    "El ajedrez, considerado tanto un juego como un arte y una ciencia, ha fascinado a filosofos, matematicos y estrategas durante mas de quince siglos. Originario de la India antigua, donde se conocia como chaturanga, el juego evoluciono mientras viajaba por Persia, el mundo arabe y finalmente Europa, donde adquirio las reglas modernas que conocemos hoy. La aparente simplicidad de su configuracion un tablero de sesenta y cuatro casillas y treinta y dos piezas con movimientos definidos—contrasta con la asombrosa complejidad que emerge durante el juego. Matematicamente, el numero de posibles partidas de ajedrez excede la cantidad de atomos en el universo observable, lo que explica por que incluso con los avances en inteligencia computacional, el ajedrez sigue presentando desafios unicos para la mente humana. Los grandes maestros desarrollan una comprension intuitiva de patrones y posiciones que trascienden el calculo puro, combinando memoria, visualizacion espacial y pensamiento estrategico a largo plazo. Mas alla de su valor como competicion, el ajedrez ha servido como metafora recurrente para el conflicto humano, la politica internacional y la vida misma, apareciendo en innumerables obras literarias y filosoficas que exploran temas de destino, libre albedrio y la tension entre calculo racional y creatividad intuitiva.",
  ],
  'competitive': [
    "La exploracion espacial, que comenzo como una competencia geopolitica durante la Guerra Fria, se ha transformado en un esfuerzo colaborativo internacional con implicaciones profundas para nuestra comprension del universo y nuestro lugar en el. El alunizaje del Apollo 11 en 1969 marco un hito en la historia humana, demostrando nuestra capacidad para superar las limitaciones terrestres y expandir nuestra presencia mas alla de la atmosfera de nuestro planeta. Desde entonces, misiones roboticas han explorado los confines del sistema solar, revelando oceanos subterraneos en lunas de Jupiter que podrian albergar vida microbiana, y telescopios espaciales como el Hubble han capturado imagenes de galaxias formadas poco despues del Big Bang, expandiendo exponencialmente nuestro entendimiento cosmologico. La Estacion Espacial Internacional representa un logro diplomatico y tecnologico sin precedentes, donde astronautas de naciones historicamente rivales conviven y colaboran en investigaciones que benefician a toda la humanidad. Los recientes desarrollos en el sector espacial privado estan reduciendo dramaticamente los costos de acceso al espacio, democratizando oportunidades antes limitadas a superpotencias y abriendo posibilidades para la mineria de asteroides, el turismo orbital y eventualmente colonias permanentes en la Luna y Marte. Mientras contemplamos estos futuros escenarios, surgen cuestiones eticas, legales y filosoficas fundamentales sobre la preservacion de entornos extraterrestres, la distribucion equitativa de recursos cosmicos y la posible transformacion de la identidad humana al convertirnos en una especie multiplanetaria."
  ]
};

// Textos originales
export const typingTexts = [
  'Los parques nacionales preservan ecosistemas naturales para las generaciones futuras. Estos espacios protegidos permiten a los visitantes conectar con la naturaleza mientras aprenden sobre la importancia de la conservacion ambiental.',
  'La fotografia es una forma de arte que captura momentos efimeros y los convierte en recuerdos permanentes. Con la tecnologia actual, cualquier persona puede experimentar con diferentes estilos y tecnicas fotograficas.',
  'Cocinar en casa no solo es mas economico sino tambien mas saludable que comer fuera regularmente. Aprender tecnicas culinarias basicas puede transformar ingredientes simples en platos deliciosos y nutritivos.',
  'El ciclismo urbano representa una alternativa sostenible al transporte motorizado. Ademas de reducir emisiones, ofrece beneficios para la salud fisica y mental, contribuyendo a ciudades mas habitables.'
]; 